### ISSUE TITLE
Where does the BMP Name and Number stem from?

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#136]
@leeensminger Can you let me know where the BMP Number and Name are populated? There is not an option for this in ES2M. You can only add the BMP type and checklist. Currently, all the BMPs show the same Number and Name.

![question](https://user-images.githubusercontent.com/16418393/38373657-45e52f38-38e1-11e8-8075-65b0738c3819.png)

**Comment by leeensminger** [comment]
@impittman in the same sql connection, change database to es2m_bmps.  I believe there's only one feature class in there.

**Comment by impittman** [comment]
@leeensminger I may be misinterpreting ES2M functions, but have further questions after reviewing the es2m_bmp database. 
Currently, 3 BMPs exist in the feature class. I presume these are created elsewhere and not within ES2M. However, there is currently no way that I can find to associate a specific BMP to a Project in ES2M. So when you assign a BMP type to a project in Admin or Inspection, it just assigns the BMP with a matching type it appears. Since there are only 3 BMPs with differing types, there is no way to discern how the BMP is assigned, meaning is the first BMP in the database with the matching type assigned?

Additionally, if you change the BMP type of a Project in the Admin section or Inspection section, all BMPs that were initially assigned that BMP change too since differentiation/assignment of BMP appears not to occur. Here are the steps as it may be easier to replicate:
-Click Admin - Project
-Select a Project from the list - note its BMP Number and Type. Focus on the following 3 in the screenshot below as they have the same BMP number since a relationship is not created to assign a specific BMP. The projects are also not in the same area geographically speaking.
![testcase](https://user-images.githubusercontent.com/16418393/38420671-0e75beba-3994-11e8-9477-5aac20903f6b.png)


-Select one project from the list above, Click on the "SWM Facilities" tab and edit the BMP type/click save.
-Review the other Projects noted above and you will see the type changed for all since the relationship to define a BMP to a Project is missing.

**Comment by leeensminger** [comment]
@impittman @ehsan67 The actual forms are now located here: M:\2014\17141728.A\Reports\ES2M\Documents\Inspection Forms Collection\Construction Checklists\PDF Forms

The forms match to BMPs per the table below.  Note there are many gaps - this is all we have for now.


BMP Type | Form filename
-- | --
Bioretention | DelDOT Bioretention   Facility Construction Checklist
Infiltration   Trench | DelDOT Infiltration   Trench Construction Checklist
Wet Pond | DelDOT Stormwater   Basin Construction Checklist
Dry Pond | DelDOT Stormwater   Basin Construction Checklist
Wet Pond /   Wetland | DelDOT Stormwater   Basin Construction Checklist
Infiltration   Basin | DelDOT Stormwater   Basin Construction Checklist
Filter Strip | DelDOT Veg Channel or   Bioswale Construction Checklist
Biofiltration   Swale | DelDOT Veg Channel or   Bioswale Construction Checklist

The workflow is below.  This workflow starts from a scenario where for the given BMP, this is the first checklist that is completed.
1. User selects a BMP from the SWM Facilities list.  User selects Download Current Checklist (this doesn't exist in UI yet).
2. Since this is the first time the user has downloaded the checklist for this BMP, the system gets the template (empty form), based upon the correct BMP type, and provides this as a download to the user.  
3. The user PARTIALLY fills out the form for the day.
4. The user uploads the file (user clicks "Select File", browses to the PDF they have updated and saved locally, and selects this file), and clicks "Upload Revised Checklist".
5. The system takes the uploaded file, saves it to the system as associated to the selected BMP.  
**Note - between steps 4 and 5, the system tracks this using a key ID.  BC or Lu would have more details about the technical implementation.
6. Later (the next inspection, 1-2 weeks later), the user is back in the field.  The user selects the same BMP and clicks the Download Current Checklist button (again, not in UI yet).  The system finds the checklist for that BMP that was most recently updated (in step 5 above), and returns this as a web download to the user.
7. The user repeats steps 4 and 5 from above.  In this way, the checklist for a given BMP is filled out over time, and the user downloads and uploads the form as they go.

Let's meet and discuss with followup questions.

**Comment by leeensminger** [comment]
So @ehsan67 action items, I think, are:

- [ ] Kill the existing template files, and replace using those provided in the link above.
- [ ] Implement the Download Current Checklist UI functionality.
- [ ] Update the Admin/Config page to only show the BMP types for which we have a form.  Ensure the Download Current Checklist button (present on this page) returns the correct, new checklist template document.
- [ ] Work with Maria to verify the functionality works as documented above.

**Comment by leeensminger** [comment]
@impittman @ehsan67 The BMPs are populated and loaded in the system in another (future) module - Design BMP.  Now, we (KCI) are loading BMPs into the system, and associating these to the Projects in a manual way.  We don't have any current data, since this is a day-forward system.  

@impittman You mentioned that editing BMP type changes ALL BMPs.  The association for BMPs/Contracts I believe is held in es2m.REF_ProjectBMPs.  Please confirm this issue, and if still present, please create a new bug for Ehsan (separate from this issue), and clearly document the issue and steps to reproduce.

**Comment by ehsan67** [comment]
@leeensminger @impittman  can you explain how we assign the first bmp to a project? The ui doesn't allow to add bmp and it is only possible to edit the currently assigned bmp for projects. On the other hand, the database design support multiple BMP for project. It is a M to N relationship which means that one BMP can be related to multiple projects

**Comment by leeensminger** [comment]
@ehsan67 BMPs are not assigned or associated to projects in this UI.  The process to do so will occur in a future module, that isn't built yet.  So for now, KCI will just be manually loading the database and assigning the contract ID for those BMPs as appropriate.  

a M:N relationship between projects and BMPs is not a feasible business process that would occur - that said, a M:N still works, and the UI of the future module should handle this, and I don't think we have to change the data model at this time.

**Comment by ehsan67** [comment]
@impittman  kci ready, I removed all submitted checklists in the database

**Comment by impittman** [comment]
this was updated on testing, closing issue
