### ISSUE TITLE
"To" field in IRF first page is missing

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#160]
@impittman please check back to the source IRF (I can send link, if needed) or requirements, and confirm how the "To" field on the first page of the report is intended to be populated.

This field was blank for me - maybe because I did not have any of the project team populated??  Please confirm, and assign to Gerry if you think this is really an issue.

**Comment by impittman** [comment]
@leeensminger I have the project team populated and the "to" was also missing. If you have the link to the requirements, please send along.

**Comment by impittman** [comment]
I found the mockup for the IRF Form. Within is the following comment for the “To” field. Is this field still only to show the Project Supervisor or has anything changed from DelDOT feedback since we are now emailing all Project Team Members? If these comments are good, I will assign to Gerry.

![comments](https://user-images.githubusercontent.com/16418393/53344185-0f2dcb80-38e0-11e9-926b-609e487fe68f.png)

**Comment by leeensminger** [comment]
@impittman those comments are good

**Comment by impittman** [comment]
@leeensminger Based on  your feedback on the comments I found: I tested by assigning a Project Superintendent to the new project. Submitted an inspection and the "To" field was filled out correctly in the report. I think the problem in the other project inspection was there was not a project superintendent assigned and believe this is working as it should.
![to screenshot](https://user-images.githubusercontent.com/16418393/53412186-b10fef80-3996-11e9-923e-8c5b0799b73e.png)

**Comment by impittman** [comment]
@leeensminger as a heads up, this is back to not working. I will forward off to Gerry.

**Comment by impittman** [comment]
@gerrykelly 
Currently, the IRF reports are not populating the "To" field. This was working at an earlier date (see example above). The To field should be populated on the report by:
1) Using the name of the Project Superintendent  - this role is assigned in the field "Project Roles Id" in the screenshot below where the Projects_Roles_ID = 6 
2) Using the associated Company Name of the Project Superintendent, field is "CompanyorGroup"

**Table to Use:**
![image](https://user-images.githubusercontent.com/16418393/53641508-3268bb80-3bfd-11e9-87ee-8136e410a495.png)

**Comment by gerrykelly** [comment]
@impittman 
I think this was still working OK.  For any IRF related to contract 26 you will not get a value for TO.  For anything related to 26 it's a data issue since you have 2 records for Projects_Roles_ID = 6 and one has an invalid user ID (so the name is retrieved as NULL).  I revised the code to get the other non-NULL value so it works in this case now, but really the fix is QC on the data side.

**Comment by impittman** [comment]
@gerrykelly  Thanks for checking on this. I didn't realize having 2 project superintendents would be an issue. This is definitely something to pass along to the enduser and glad it was caught in testing. 
I re-tested and all is working as expected. Closing.
