### ISSUE TITLE
Insert action button to generate IRF PDF from Inspections>Projects>Inspections

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#162]
Similar to #147 

@kanglu666 please add an action button within the grid, that allows users to generate the PDF report on-demand for any submitted inspection.  When an inspection has not been submitted, either disable the action button, or display a message indicating that the report cannot be generated until the form has been submitted.

![image](https://user-images.githubusercontent.com/4103847/53329632-7df82e00-38ba-11e9-8bab-b49de8b4355f.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by impittman** [comment]
The download report button acts as outlined. If an inspection has not been  submitted, a message is generated to show a report must be submitted first. Inspections that are submitted and the reports have been created are downloaded successfully. The inspection reports for Construction, Regulatory Review, Semi-Final, and Final Inspections were not generated and I believe the reason is as previously noted, the reports have yet to be completed for use in the System.

**Only one change to note:**

@kanglu666 - Please update the message below by getting rid of the "**.**" before the !
![fix message](https://user-images.githubusercontent.com/16418393/53732389-ccbe3e80-3e4b-11e9-9491-2aa933396d7c.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by impittman** [comment]
updated, no issues.
